### ISSUE TITLE
1.21.3 Tracking

### ISSUE THREAD

**Issue by Dreeam-qwq** [Dreeam-qwq/Leaf#122]
### What feature do you want to see added?

- [x] First Paper 1.21.2/3 build / run success

24w33a:
- [ ] ~~[MC-275437](https://bugs.mojang.com/browse/MC-275437) (24w33a <-> 24w36a)~~
- [x] [MC-59471](https://bugs.mojang.com/browse/MC-59471), [MC-129055](https://bugs.mojang.com/browse/MC-129055) (If Paper didn't handle it)
- [x] [MC-183518](https://bugs.mojang.com/browse/MC-183518) (Backport to 1.21.1)
- [ ] ~~[MC-269814](https://bugs.mojang.com/browse/MC-269814) (Backport to 1.21.1)~~
- [ ] ~~[MC-156579](https://bugs.mojang.com/browse/MC-156579) (Backport to 1.21.1)~~

24w27a:
- [X] EnderPearl can force load chunks (see Paper/pull/11524)

Bugs need to fix:
- [x] #152 Water physics bug

**Comment by At87668** [comment]
I don't like **EnderPearl can force load chunks**
Can you add a disable option in config?

Thanks.

**Comment by Dreeam-qwq** [comment]
> I don't like **EnderPearl can force load chunks** Can you add a disable option in config?
> 
> Thanks.

Which you mentioned just listed in this Tracking list and planed to do.

**Comment by Justiks1337** [comment]
When first 1.21.3 build?

**Comment by Dreeam-qwq** [comment]
> When first 1.21.3 build?

When the author of Leaf update it to 1.21.3

**Comment by Justiks1337** [comment]
бля бро мне дата нужна 🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷  🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷🐷

**Comment by Gauvino** [comment]
All issues on mojang as been fixed is there anything more to wait to release a 1.21.3?

**Comment by Dreeam-qwq** [comment]
> All issues on mojang as been fixed is there anything more to wait to release a 1.21.3?

Wait me to have enough time to update it. be patient. And also you can see, we are still researching and adding more optimizations on 1.21.1

**Comment by Dreeam-qwq** [comment]
Probably begin 1.21.3 update during winter break, since I dont't have enough time recently.

**Comment by ghost** [comment]
A one year ago: leaf updated to 1.21.3🤣

**Comment by Dreeam-qwq** [comment]
> A one year ago: leaf updated to 1.21.3🤣

You can see we are still committing 1.12.1, not no thing to do🤔

And I already said above, begin update during winter break, and also 1.21.4

**Comment by Cqmmls** [comment]
最新构建版Citizens-2.0.36-b3641好像无法在 最新的leaf加载，提示无此版本NMS

**Comment by ghost** [comment]
> 最新构建版Citizens-2.0.36-b3641好像无法在 最新的leaf加载，提示无此版本NMS

what

**Comment by Dreeam-qwq** [comment]
> 最新构建版Citizens-2.0.36-b3641好像无法在 最新的leaf加载，提示无此版本NMS

首先Citizens最新版不支持1.21.1，其次Citizens最新版是b3644，然后1.21.1请使用b3598。
另外下次反馈问题请https://github.com/Winds-Studio/Leaf/issues/new/choose

**Comment by Gauvino** [comment]
This can be closed right ?

**Comment by Dreeam-qwq** [comment]
> This can be closed right ?

No, I didn't add configurable tripwire dupe back yet.
